-- db/migrations/071_aws_accounts_credential_columns.sql
--
-- Audit d01 finding: aws_accounts.client_secret / gcp_service_account_key
-- are actively used throughout app/api/cspm.py, app/azure/discovery.py,
-- app/azure/provider.py, app/azure/metrics_collector.py, and
-- app/admin/accounts.py -- but the ONLY place that creates them today is
-- the repo-root 010_multi_cloud_credentials.sql, which is explicitly NOT
-- a tracked migration ("Do not run this file directly -- use
-- apply_multi_cloud_credentials.py") and lives outside db/migrations/,
-- so migrate.py's `*.sql` glob never sees it.
--
-- (aws_accounts.status was also checked against this same concern and is
-- fine: it's already present in db_schema_only.sql -- the real bootstrap
-- source setup.sh/deploy.sh actually load, per their own comments -- so
-- it doesn't need a migration here. db/schema.sql, the OTHER schema file
-- in this repo, is stale and does not reflect this; do not use it as a
-- reference for what a fresh install actually gets.)
--
-- A fresh install or disaster-recovery restore that only runs the
-- documented standard deploy path (`migrate.py apply --all-pending`)
-- would silently end up without Azure/GCP credential storage at all,
-- with every Azure/GCP account failing at the first action that needs a
-- secret. This migration promotes that same, unchanged ALTER into the
-- tracked path so it actually runs everywhere. AFTER client_id / AFTER
-- service_account_email match 009_multi_cloud_provider_columns.sql's
-- column order exactly.
--
-- Idempotent (MySQL 8 direct syntax, same as 002/003/etc. in this
-- directory): a no-op wherever apply_multi_cloud_credentials.py or an
-- earlier manual ALTER already put these columns in place.
ALTER TABLE aws_accounts
    ADD COLUMN IF NOT EXISTS client_secret VARCHAR(500) DEFAULT NULL AFTER client_id,
    ADD COLUMN IF NOT EXISTS gcp_service_account_key TEXT DEFAULT NULL AFTER service_account_email;
