# app/aws/metric_catalog_data.py
"""
Source-of-truth for the CloudWatch metric catalog.

Two tiers:

  CURATED   — services with a hand-enumerated metric list (name, unit,
              statistic, short description, whether it's part of the
              recommended default onboarding template). Includes the
              'core' services this app already collects (EC2, EBS, RDS,
              ALB, Lambda, S3, ECS) plus the most commonly monitored
              'extended' AWS services.

  DIRECTORY — every remaining AWS service that publishes CloudWatch
              metrics (from "AWS services that publish CloudWatch
              metrics", the official AWS namespace list). These are
              registered by namespace only — individual metric names are
              fetched on demand per account/region via the CloudWatch
              ListMetrics API ("Discover" in the UI) rather than
              hand-typed here, since AWS adds/changes these constantly
              and only a fraction will exist in any one account.

Run `python scripts/seed_metric_catalog.py` after editing this file to
push changes into the `metric_catalog` table.
"""

# service key -> (display name, namespace, category, [ (metric_name, unit, statistic, is_default, description), ... ])
CURATED = {

    # ── Core (already collected today) ───────────────────────────
    "ec2": ("Amazon EC2", "AWS/EC2", "core", [
        ("CPUUtilization",     "Percent", "Average", True,  "% CPU used"),
        ("NetworkIn",          "Bytes",   "Average", True,  "Inbound network traffic"),
        ("NetworkOut",         "Bytes",   "Average", True,  "Outbound network traffic"),
        ("DiskReadBytes",      "Bytes",   "Sum",     False, "Instance-store disk reads"),
        ("DiskWriteBytes",     "Bytes",   "Sum",     False, "Instance-store disk writes"),
        ("StatusCheckFailed",  "Count",   "Maximum", True,  "Combined instance+system health check"),
        ("StatusCheckFailed_Instance", "Count", "Maximum", False, "Instance-level health check"),
        ("StatusCheckFailed_System",   "Count", "Maximum", False, "Underlying host health check"),
        ("CPUCreditUsage",     "Count",   "Sum",     False, "Burstable (T-class) CPU credits used"),
        ("CPUCreditBalance",   "Count",   "Average", False, "Burstable (T-class) CPU credits available"),
        ("EBSReadOps",         "Count",   "Sum",     False, "EBS read operations"),
        ("EBSWriteOps",        "Count",   "Sum",     False, "EBS write operations"),
        ("EBSReadBytes",       "Bytes",   "Sum",     False, "EBS bytes read"),
        ("EBSWriteBytes",      "Bytes",   "Sum",     False, "EBS bytes written"),
        ("MetadataNoToken",    "Count",   "Sum",     False, "IMDSv1 requests (no token) — security signal"),
        # CWAgent-published, not standard EC2 namespace -- only present
        # for instances with the CloudWatch Agent actually installed and
        # reporting (see collector_direct.py's _ec2_cwagent_installed).
        # is_default=False deliberately -- unlike CPUUtilization/etc,
        # which apply to every instance, this is opt-in since it doesn't
        # exist at all for instances without the agent. metric_name uses
        # CWAgent's own literal published name (snake_case, not the
        # PascalCase convention of standard EC2 metrics) for consistency
        # with the official platform naming, matching this session's
        # broader naming-consistency work. See apply_add_cwagent_mem_threshold.py.
        ("mem_used_percent",   "Percent", "Average", False, "Memory utilization (requires CloudWatch Agent)"),
        # disk_used_percent: same rationale as mem_used_percent above
        # (CWAgent-published, opt-in, snake_case official name) -- but
        # published PER MOUNT POINT (multiple series per instance if
        # more than one is monitored). The scheduled collector prefers
        # the root filesystem ("/" / "C:") when multiple exist, matching
        # what the Services page chart already does for the same reason
        # -- "disk space utilized" as a single dashboard number means
        # the root volume to anyone glancing at it. See
        # apply_add_cwagent_disk_threshold.py.
        ("disk_used_percent",  "Percent", "Average", False, "Disk space utilized, root filesystem (requires CloudWatch Agent)"),
    ]),
    "ebs": ("Amazon EBS", "AWS/EBS", "core", [
        ("VolumeReadOps",       "Count",   "Average", True,  "Read operations/sec"),
        ("VolumeWriteOps",      "Count",   "Average", True,  "Write operations/sec"),
        ("VolumeReadBytes",     "Bytes",   "Average", False, "Bytes read"),
        ("VolumeWriteBytes",    "Bytes",   "Average", False, "Bytes written"),
        ("VolumeQueueLength",   "Count",   "Average", True,  "I/O requests waiting — bottleneck signal"),
        ("BurstBalance",        "Percent", "Average", True,  "gp2 burst credit balance"),
        ("VolumeIdleTime",      "Seconds", "Average", False, "Time volume was idle"),
        ("VolumeThroughputPercentage",  "Percent", "Average", False, "io1/io2 throughput used vs provisioned"),
        ("VolumeConsumedReadWriteOps",  "Count",   "Average", False, "Consumed IOPS toward provisioned limit"),
        ("VolumeTotalReadTime",  "Seconds", "Average", False, "Total seconds spent on read ops"),
        ("VolumeTotalWriteTime", "Seconds", "Average", False, "Total seconds spent on write ops"),
    ]),
    "rds": ("Amazon RDS", "AWS/RDS", "core", [
        ("CPUUtilization",        "Percent", "Average", True,  "% CPU used"),
        ("DatabaseConnections",   "Count",   "Average", True,  "Active DB connections"),
        ("FreeStorageSpace",      "Bytes",   "Average", True,  "Remaining allocated storage"),
        ("ReadIOPS",              "Count/Second", "Average", True,  "Read I/O operations/sec"),
        ("WriteIOPS",             "Count/Second", "Average", True,  "Write I/O operations/sec"),
        ("ReadLatency",           "Seconds", "Average", True,  "Avg time per read op"),
        ("WriteLatency",          "Seconds", "Average", True,  "Avg time per write op"),
        ("FreeableMemory",        "Bytes",   "Average", True,  "RAM available to the DB engine"),
        ("SwapUsage",             "Bytes",   "Average", False, "Swap space used"),
        ("DiskQueueDepth",        "Count",   "Average", False, "Outstanding I/O requests"),
        ("ReplicaLag",            "Seconds", "Average", False, "Read-replica lag behind primary"),
        ("BinLogDiskUsage",       "Bytes",   "Average", False, "MySQL/MariaDB binlog disk usage"),
        ("TransactionLogsDiskUsage", "Bytes", "Average", False, "PostgreSQL WAL disk usage"),
        ("BurstBalance",          "Percent", "Average", False, "gp2 storage burst credit balance"),
        ("CPUCreditBalance",      "Count",   "Average", False, "Burstable-class CPU credits"),
        ("DatabaseConnectionsBorrowLatency", "Seconds", "Average", False, "RDS Proxy connection borrow latency"),
    ]),
    "alb": ("Application Load Balancer", "AWS/ApplicationELB", "core", [
        ("RequestCount",                    "Count",   "Sum",     True,  "Total requests received"),
        ("TargetResponseTime",              "Seconds", "Average", True,  "Latency from ALB to target"),
        ("HealthyHostCount",                "Count",   "Average", True,  "Targets passing health checks"),
        ("UnHealthyHostCount",              "Count",   "Average", True,  "Targets failing health checks"),
        ("HTTPCode_Target_2XX_Count",       "Count",   "Sum",     False, "Successful target responses"),
        ("HTTPCode_Target_4XX_Count",       "Count",   "Sum",     True,  "Client-error target responses"),
        ("HTTPCode_Target_5XX_Count",       "Count",   "Sum",     True,  "Server-error target responses"),
        ("HTTPCode_ELB_5XX_Count",          "Count",   "Sum",     False, "Errors generated by the LB itself"),
        ("ActiveConnectionCount",           "Count",   "Sum",     False, "Concurrent TCP connections"),
        ("NewConnectionCount",              "Count",   "Sum",     False, "New TCP connections established"),
        ("RejectedConnectionCount",         "Count",   "Sum",     False, "Connections rejected (LB at capacity)"),
        ("TargetConnectionErrorCount",      "Count",   "Sum",     False, "Failed connections to targets"),
    ]),
    "nlb": ("Network Load Balancer", "AWS/NetworkELB", "extended", [
        ("ActiveFlowCount",      "Count", "Average", False, "Concurrent flows"),
        ("NewFlowCount",         "Count", "Sum",     False, "New flows established"),
        ("HealthyHostCount",     "Count", "Average", True,  "Targets passing health checks"),
        ("UnHealthyHostCount",   "Count", "Average", True,  "Targets failing health checks"),
        ("ProcessedBytes",       "Bytes", "Sum",     False, "Total bytes processed"),
        ("TCP_Client_Reset_Count", "Count", "Sum",   False, "TCP resets from clients"),
    ]),
    "lambda": ("AWS Lambda", "AWS/Lambda", "core", [
        ("Invocations",         "Count",   "Sum",     True,  "Function invocations"),
        ("Errors",              "Count",   "Sum",     True,  "Failed invocations"),
        ("Duration",            "Milliseconds", "Average", True, "Execution time"),
        ("Throttles",           "Count",   "Sum",     True,  "Requests throttled by concurrency limit"),
        ("ConcurrentExecutions","Count",   "Maximum", False, "Concurrent executions in-flight"),
        ("IteratorAge",         "Milliseconds", "Average", False, "Stream-trigger processing lag"),
        ("DeadLetterErrors",    "Count",   "Sum",     False, "Failed to write to configured DLQ"),
        ("ColdStart",           "Count",   "Sum",     False, "Cold-start init invocations (custom metric on some setups)"),
    ]),
    "s3": ("Amazon S3", "AWS/S3", "core", [
        ("BucketSizeBytes",           "Bytes", "Average", True,  "Total bucket size (daily storage metric)"),
        ("NumberOfObjects",           "Count", "Average", True,  "Object count (daily storage metric)"),
        ("AllRequests",               "Count", "Sum",     False, "All requests (needs request metrics enabled)"),
        ("4xxErrors",                 "Count", "Sum",     False, "Client-error requests"),
        ("5xxErrors",                 "Count", "Sum",     False, "Server-error requests"),
        ("FirstByteLatency",          "Milliseconds", "Average", False, "Time to first response byte"),
        ("TotalRequestLatency",       "Milliseconds", "Average", False, "End-to-end request latency"),
    ]),
    "ecs": ("Amazon ECS", "AWS/ECS", "core", [
        ("CPUUtilization",     "Percent", "Average", True,  "% of task/service CPU reservation used"),
        ("MemoryUtilization",  "Percent", "Average", True,  "% of task/service memory reservation used"),
        ("RunningTaskCount",   "Count",   "Average", False, "Tasks currently running (Container Insights)"),
        ("PendingTaskCount",   "Count",   "Average", False, "Tasks waiting to be placed (Container Insights)"),
    ]),

    # ── Extended (curated, common services) ──────────────────────
    "apigateway": ("Amazon API Gateway", "AWS/ApiGateway", "extended", [
        ("Count",         "Count",        "Sum",     True,  "Total API calls"),
        ("4XXError",       "Count",       "Sum",     True,  "Client errors"),
        ("5XXError",       "Count",       "Sum",     True,  "Server errors"),
        ("Latency",         "Milliseconds", "Average", True, "End-to-end request latency"),
        ("IntegrationLatency", "Milliseconds", "Average", False, "Backend integration latency"),
        ("CacheHitCount",   "Count",      "Sum",     False, "API cache hits"),
        ("CacheMissCount",  "Count",      "Sum",     False, "API cache misses"),
    ]),
    "dynamodb": ("Amazon DynamoDB", "AWS/DynamoDB", "extended", [
        ("ConsumedReadCapacityUnits",  "Count", "Sum",     True,  "RCUs consumed"),
        ("ConsumedWriteCapacityUnits", "Count", "Sum",     True,  "WCUs consumed"),
        ("ThrottledRequests",          "Count", "Sum",     True,  "Requests throttled"),
        ("ReadThrottleEvents",         "Count", "Sum",     False, "Read throttle events"),
        ("WriteThrottleEvents",        "Count", "Sum",     False, "Write throttle events"),
        ("SuccessfulRequestLatency",   "Milliseconds", "Average", False, "Request latency"),
        ("SystemErrors",               "Count", "Sum",     False, "5xx errors from DynamoDB"),
        ("UserErrors",                 "Count", "Sum",     False, "4xx errors (bad requests)"),
        ("ConditionalCheckFailedRequests", "Count", "Sum", False, "Conditional write failures"),
    ]),
    "sqs": ("Amazon SQS", "AWS/SQS", "extended", [
        ("ApproximateNumberOfMessagesVisible", "Count", "Average", True, "Messages available to consume"),
        ("ApproximateAgeOfOldestMessage",      "Seconds", "Maximum", True, "Oldest unprocessed message age"),
        ("NumberOfMessagesSent",               "Count", "Sum", False, "Messages sent"),
        ("NumberOfMessagesReceived",           "Count", "Sum", False, "Messages received"),
        ("NumberOfMessagesDeleted",            "Count", "Sum", False, "Messages deleted"),
        ("NumberOfEmptyReceives",              "Count", "Sum", False, "Empty poll responses"),
        ("ApproximateNumberOfMessagesNotVisible", "Count", "Average", False, "In-flight messages"),
    ]),
    "sns": ("Amazon SNS", "AWS/SNS", "extended", [
        ("NumberOfMessagesPublished", "Count", "Sum", True,  "Messages published"),
        ("NumberOfNotificationsFailed", "Count", "Sum", True, "Failed deliveries"),
        ("NumberOfNotificationsDelivered", "Count", "Sum", False, "Successful deliveries"),
        ("PublishSize", "Bytes", "Average", False, "Message payload size"),
    ]),
    "cloudfront": ("Amazon CloudFront", "AWS/CloudFront", "extended", [
        ("Requests",          "Count",   "Sum",     True,  "Viewer requests"),
        ("BytesDownloaded",   "Bytes",   "Sum",     False, "Bytes served to viewers"),
        ("BytesUploaded",     "Bytes",   "Sum",     False, "Bytes uploaded by viewers"),
        ("4xxErrorRate",      "Percent", "Average", True,  "% of requests resulting in 4xx"),
        ("5xxErrorRate",      "Percent", "Average", True,  "% of requests resulting in 5xx"),
        ("TotalErrorRate",    "Percent", "Average", False, "% of requests resulting in error"),
        ("OriginLatency",     "Milliseconds", "Average", False, "Time to first byte from origin"),
        ("CacheHitRate",      "Percent", "Average", False, "% served from edge cache"),
    ]),
    "elasticache": ("Amazon ElastiCache", "AWS/ElastiCache", "extended", [
        ("CPUUtilization",       "Percent", "Average", True,  "% CPU used"),
        ("DatabaseMemoryUsagePercentage", "Percent", "Average", True, "% memory used (Redis)"),
        ("CurrConnections",      "Count",   "Average", True,  "Current client connections"),
        ("Evictions",            "Count",   "Sum",     True,  "Keys evicted due to memory pressure"),
        ("CacheHits",            "Count",   "Sum",     False, "Cache hits"),
        ("CacheMisses",          "Count",   "Sum",     False, "Cache misses"),
        ("ReplicationLag",       "Seconds", "Average", False, "Redis replica lag"),
        ("SwapUsage",            "Bytes",   "Average", False, "Swap used"),
        ("NetworkBytesIn",       "Bytes",   "Average", False, "Inbound network traffic"),
        ("NetworkBytesOut",      "Bytes",   "Average", False, "Outbound network traffic"),
    ]),
    "opensearch": ("Amazon OpenSearch Service", "AWS/ES", "extended", [
        ("ClusterStatus.green",  "Count",   "Maximum", False, "Cluster healthy"),
        ("ClusterStatus.yellow", "Count",   "Maximum", True,  "Cluster degraded (replica shards unassigned)"),
        ("ClusterStatus.red",    "Count",   "Maximum", True,  "Cluster critical (primary shards unassigned)"),
        ("CPUUtilization",       "Percent", "Average", True,  "% CPU used"),
        ("JVMMemoryPressure",    "Percent", "Average", True,  "% JVM heap used"),
        ("FreeStorageSpace",     "Megabytes","Minimum", True,  "Free disk space"),
        ("ClusterIndexWritesBlocked", "Count", "Maximum", True, "Writes blocked (disk/heap pressure)"),
        ("Nodes",                "Count",   "Average", False, "Node count"),
        ("SearchLatency",        "Milliseconds", "Average", False, "Search request latency"),
        ("IndexingLatency",      "Milliseconds", "Average", False, "Indexing request latency"),
    ]),
    "eks": ("Amazon EKS", "AWS/EKS", "extended", [
        ("cluster_failed_node_count", "Count", "Average", True, "Nodes not Ready"),
        ("cluster_node_count",        "Count", "Average", False, "Total nodes in cluster"),
    ]),
    "efs": ("Amazon EFS", "AWS/EFS", "extended", [
        ("PercentIOLimit",       "Percent", "Average", True,  "% of provisioned I/O used"),
        ("BurstCreditBalance",   "Bytes",   "Average", True,  "Burst throughput credits available"),
        ("ClientConnections",    "Count",   "Sum",     False, "Active NFS client connections"),
        ("StorageBytes",         "Bytes",   "Average", False, "Total filesystem size"),
        ("DataReadIOBytes",      "Bytes",   "Sum",     False, "Bytes read"),
        ("DataWriteIOBytes",     "Bytes",   "Sum",     False, "Bytes written"),
    ]),
    "documentdb": ("Amazon DocumentDB", "AWS/DocDB", "extended", [
        ("CPUUtilization",     "Percent", "Average", True,  "% CPU used"),
        ("DatabaseConnections","Count",   "Average", True,  "Active connections"),
        ("FreeableMemory",     "Bytes",   "Average", True,  "RAM available"),
        ("VolumeBytesUsed",    "Bytes",   "Average", False, "Cluster storage used"),
        ("BufferCacheHitRatio","Percent", "Average", False, "Buffer cache hit rate"),
    ]),
    "neptune": ("Amazon Neptune", "AWS/Neptune", "extended", [
        ("CPUUtilization",     "Percent", "Average", True,  "% CPU used"),
        ("GremlinRequestsPerSec", "Count/Second", "Average", False, "Gremlin request rate"),
        ("SparqlRequestsPerSec",  "Count/Second", "Average", False, "SPARQL request rate"),
        ("VolumeBytesUsed",    "Bytes",   "Average", False, "Cluster storage used"),
    ]),
    "msk": ("Amazon MSK", "AWS/Kafka", "extended", [
        ("CpuUser",              "Percent", "Average", True,  "% CPU used (user)"),
        ("KafkaDataLogsDiskUsed","Percent", "Average", True,  "% broker disk used"),
        ("UnderReplicatedPartitions","Count","Sum",     True,  "Partitions under-replicated"),
        ("OfflinePartitionsCount","Count",  "Sum",      True,  "Partitions offline"),
        ("BytesInPerSec",        "Bytes/Second","Average", False, "Broker inbound throughput"),
        ("BytesOutPerSec",       "Bytes/Second","Average", False, "Broker outbound throughput"),
    ]),
    "kinesis": ("Amazon Kinesis Data Streams", "AWS/Kinesis", "extended", [
        ("IncomingBytes",        "Bytes",   "Sum",  True,  "Bytes ingested"),
        ("IncomingRecords",      "Count",   "Sum",  True,  "Records ingested"),
        ("ReadProvisionedThroughputExceeded",  "Count", "Sum", True, "Read throttling"),
        ("WriteProvisionedThroughputExceeded", "Count", "Sum", True, "Write throttling"),
        ("GetRecords.IteratorAgeMilliseconds", "Milliseconds", "Maximum", False, "Consumer processing lag"),
    ]),
    "firehose": ("Amazon Data Firehose", "AWS/Firehose", "extended", [
        ("DeliveryToS3.Success",   "Percent", "Average", True,  "% of records delivered successfully"),
        ("IncomingBytes",          "Bytes",   "Sum",     False, "Bytes ingested"),
        ("IncomingRecords",        "Count",   "Sum",     False, "Records ingested"),
        ("DeliveryToS3.DataFreshness", "Seconds", "Maximum", False, "Age of oldest undelivered record"),
    ]),
    "autoscaling": ("EC2 Auto Scaling", "AWS/AutoScaling", "extended", [
        ("GroupInServiceInstances", "Count", "Average", True, "Healthy running instances"),
        ("GroupDesiredCapacity",    "Count", "Average", False, "Desired capacity"),
        ("GroupMinSize",            "Count", "Average", False, "Configured minimum"),
        ("GroupMaxSize",            "Count", "Average", False, "Configured maximum"),
        ("GroupPendingInstances",   "Count", "Average", False, "Instances launching"),
        ("GroupTerminatingInstances","Count","Average", False, "Instances terminating"),
    ]),
    "natgateway": ("NAT Gateway", "AWS/NATGateway", "extended", [
        ("BytesOutToDestination", "Bytes", "Sum", True, "Outbound bytes"),
        ("BytesInFromSource",     "Bytes", "Sum", True, "Inbound bytes"),
        ("ErrorPortAllocation",   "Count", "Sum", True, "Port allocation errors (NAT exhaustion)"),
        ("ActiveConnectionCount", "Count", "Average", False, "Concurrent active connections"),
        ("PacketsDropCount",      "Count", "Sum", False, "Dropped packets"),
    ]),
    "transitgateway": ("Transit Gateway", "AWS/TransitGateway", "extended", [
        ("BytesIn",   "Bytes", "Sum", True, "Inbound bytes"),
        ("BytesOut",  "Bytes", "Sum", True, "Outbound bytes"),
        ("PacketDropCountBlackhole", "Count", "Sum", True, "Packets dropped (blackhole route)"),
        ("PacketDropCountNoRoute",   "Count", "Sum", True, "Packets dropped (no route)"),
    ]),
    "route53": ("Amazon Route 53", "AWS/Route53", "extended", [
        ("HealthCheckStatus",       "Count",   "Minimum", True, "Health check pass(1)/fail(0)"),
        ("HealthCheckPercentageHealthy", "Percent", "Average", False, "% of checking regions reporting healthy"),
        ("ConnectionTime",          "Milliseconds", "Average", False, "TCP connection time"),
    ]),
    "wafv2": ("AWS WAF", "AWS/WAFV2", "extended", [
        ("AllowedRequests", "Count", "Sum", False, "Requests allowed"),
        ("BlockedRequests", "Count", "Sum", True,  "Requests blocked"),
        ("CountedRequests", "Count", "Sum", False, "Requests matched in count mode"),
        ("PassedRequests",  "Count", "Sum", False, "Requests passed through"),
    ]),
    "redshift": ("Amazon Redshift", "AWS/Redshift", "extended", [
        ("CPUUtilization",       "Percent", "Average", True, "% CPU used"),
        ("PercentageDiskSpaceUsed", "Percent", "Average", True, "% disk used"),
        ("DatabaseConnections",  "Count",   "Average", True, "Active connections"),
        ("QueryDuration",        "Microseconds", "Average", False, "Query execution time"),
        ("ReadIOPS",             "Count/Second", "Average", False, "Read IOPS"),
        ("WriteIOPS",            "Count/Second", "Average", False, "Write IOPS"),
        ("WLMQueueLength",       "Count",   "Average", False, "Queries waiting in WLM queue"),
    ]),
    "memorydb": ("Amazon MemoryDB", "AWS/MemoryDB", "extended", [
        ("CPUUtilization",     "Percent", "Average", True, "% CPU used"),
        ("DatabaseMemoryUsagePercentage", "Percent", "Average", True, "% memory used"),
        ("CurrConnections",    "Count",   "Average", False, "Current connections"),
        ("Evictions",          "Count",   "Sum",     True,  "Keys evicted"),
    ]),
    "dax": ("DynamoDB Accelerator (DAX)", "AWS/DAX", "extended", [
        ("CPUUtilization",  "Percent", "Average", True, "% CPU used"),
        ("FaultRequestCount", "Count", "Sum", True, "Failed requests"),
        ("ItemCacheHits",   "Count",   "Sum", False, "Item cache hits"),
        ("ItemCacheMisses", "Count",   "Sum", False, "Item cache misses"),
    ]),
    "states": ("AWS Step Functions", "AWS/States", "extended", [
        ("ExecutionsFailed",    "Count", "Sum", True,  "Failed executions"),
        ("ExecutionsSucceeded", "Count", "Sum", False, "Successful executions"),
        ("ExecutionsTimedOut",  "Count", "Sum", True,  "Timed-out executions"),
        ("ExecutionThrottled",  "Count", "Sum", False, "Throttled executions"),
        ("ExecutionTime",       "Milliseconds", "Average", False, "State machine execution time"),
    ]),
    "events": ("Amazon EventBridge", "AWS/Events", "extended", [
        ("Invocations",           "Count", "Sum", True,  "Rule target invocations"),
        ("FailedInvocations",     "Count", "Sum", True,  "Failed target invocations"),
        ("ThrottledRules",        "Count", "Sum", False, "Rules throttled"),
        ("MatchedEvents",         "Count", "Sum", False, "Events matched to rules"),
    ]),
    "kms": ("AWS KMS", "AWS/KMS", "extended", [
        ("SecondsUntilKeyMaterialExpiration", "Seconds", "Minimum", False, "Time until imported key material expires"),
    ]),
    "certificatemanager": ("AWS Certificate Manager", "AWS/CertificateManager", "extended", [
        ("DaysToExpiry", "Days", "Minimum", True, "Days until certificate expiry"),
    ]),
    "backup": ("AWS Backup", "AWS/Backup", "extended", [
        ("NumberOfBackupJobsFailed",    "Count", "Sum", True,  "Failed backup jobs"),
        ("NumberOfBackupJobsCompleted", "Count", "Sum", False, "Completed backup jobs"),
        ("NumberOfRestoreJobsFailed",   "Count", "Sum", True,  "Failed restore jobs"),
    ]),
    "cognito": ("Amazon Cognito", "AWS/Cognito", "extended", [
        ("SignInSuccesses", "Count", "Sum", False, "Successful sign-ins"),
        ("SignUpSuccesses", "Count", "Sum", False, "Successful sign-ups"),
        ("ThrottledEvents", "Count", "Sum", True,  "Throttled requests"),
    ]),
    "logs": ("Amazon CloudWatch Logs", "AWS/Logs", "extended", [
        ("IncomingBytes",  "Bytes", "Sum", False, "Log bytes ingested"),
        ("IncomingLogEvents", "Count", "Sum", False, "Log events ingested"),
        ("DeliveryErrors", "Count", "Sum", True, "Subscription/export delivery errors"),
    ]),
    "vpn": ("Site-to-Site VPN", "AWS/VPN", "extended", [
        ("TunnelState",   "Count", "Maximum", True, "Tunnel up(1)/down(0)"),
        ("TunnelDataIn",  "Bytes", "Sum", False, "Bytes received"),
        ("TunnelDataOut", "Bytes", "Sum", False, "Bytes sent"),
    ]),
    "globalaccelerator": ("AWS Global Accelerator", "AWS/GlobalAccelerator", "extended", [
        ("NewFlowCount",     "Count", "Sum", False, "New flows"),
        ("ProcessedBytesIn", "Bytes", "Sum", False, "Inbound bytes processed"),
        ("ProcessedBytesOut","Bytes", "Sum", False, "Outbound bytes processed"),
    ]),
    "dms": ("AWS Database Migration Service", "AWS/DMS", "extended", [
        ("CDCLatencySource", "Seconds", "Average", True, "Replication latency from source"),
        ("CDCLatencyTarget", "Seconds", "Average", True, "Replication latency to target"),
        ("FreeableMemory",   "Bytes",   "Average", False, "Replication instance RAM available"),
        ("CPUUtilization",   "Percent", "Average", False, "Replication instance CPU used"),
    ]),
    "directconnect": ("AWS Direct Connect", "AWS/DX", "extended", [
        ("ConnectionState",         "Count", "Maximum", True, "Connection up(1)/down(0)"),
        ("ConnectionBpsEgress",     "Bits/Second", "Average", False, "Egress throughput"),
        ("ConnectionBpsIngress",    "Bits/Second", "Average", False, "Ingress throughput"),
        ("ConnectionErrorCount",    "Count", "Sum", True, "Connection errors"),
    ]),
}

# (display_service, namespace) — full AWS list, "AWS services that publish
# CloudWatch metrics": https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/aws-services-cloudwatch-metrics.html
# Anything already present in CURATED above is skipped when seeding.
DIRECTORY = [
    ("AWS Amplify", "AWS/AmplifyHosting"),
    ("AWS App Runner", "AWS/AppRunner"),
    ("WorkSpaces Applications", "AWS/AppStream"),
    ("AWS AppSync", "AWS/AppSync"),
    ("Amazon AppFlow", "AWS/AppFlow"),
    ("AWS Application Migration Service", "AWS/MGN"),
    ("Amazon Athena", "AWS/Athena"),
    ("Amazon Bedrock Guardrails", "AWS/Bedrock/Guardrails"),
    ("AWS Billing and Cost Management", "AWS/Billing"),
    ("Amazon Braket", "AWS/Braket/By Device"),
    ("AWS Private CA", "AWS/ACMPrivateCA"),
    ("Amazon Q Developer in chat applications", "AWS/Chatbot"),
    ("Amazon Chime", "AWS/ChimeVoiceConnector"),
    ("Amazon Chime SDK", "AWS/ChimeSDK"),
    ("AWS Client VPN", "AWS/ClientVPN"),
    ("AWS CloudHSM", "AWS/CloudHSM"),
    ("Amazon CloudSearch", "AWS/CloudSearch"),
    ("AWS CloudTrail", "AWS/CloudTrail"),
    ("CloudWatch agent", "CWAgent"),
    ("CloudWatch Application Signals", "ApplicationSignals"),
    ("CloudWatch metric streams", "AWS/CloudWatch/MetricStreams"),
    ("CloudWatch RUM", "AWS/RUM"),
    ("CloudWatch Synthetics", "CloudWatchSynthetics"),
    ("AWS CodeBuild", "AWS/CodeBuild"),
    ("Amazon CodeGuru Reviewer", "AWS/CodeGuruReviewer"),
    ("AWS CodePipeline", "AWS/CodePipeline"),
    ("Amazon Comprehend", "AWS/Comprehend"),
    ("AWS Config", "AWS/Config"),
    ("Connect Customer", "AWS/Connect"),
    ("Amazon Data Lifecycle Manager", "AWS/DataLifecycleManager"),
    ("AWS DataSync", "AWS/DataSync"),
    ("Amazon DevOps Guru", "AWS/DevOps-Guru"),
    ("AWS Directory Service", "AWS/DirectoryService"),
    ("Amazon EC2 Elastic Graphics", "AWS/ElasticGPUs"),
    ("Amazon EC2 Spot Fleet", "AWS/EC2Spot"),
    ("AWS Elastic Beanstalk", "AWS/ElasticBeanstalk"),
    ("Amazon Elastic Container Registry", "AWS/ECR"),
    ("Amazon ECS through CloudWatch Container Insights", "ECS/ContainerInsights"),
    ("Amazon ECS Cluster auto scaling", "AWS/ECS/ManagedScaling"),
    ("AWS Elastic Disaster Recovery", "AWS/DRS"),
    ("Amazon Elastic Inference", "AWS/ElasticInference"),
    ("Amazon EKS through CloudWatch Container Insights", "ContainerInsights"),
    ("Elastic Load Balancing (Gateway)", "AWS/GatewayELB"),
    ("Elastic Load Balancing (Classic)", "AWS/ELB"),
    ("Amazon EMR", "AWS/ElasticMapReduce"),
    ("Amazon EMR Serverless", "AWS/EMRServerless"),
    ("AWS Elemental MediaConnect", "AWS/MediaConnect"),
    ("AWS Elemental MediaConvert", "AWS/MediaConvert"),
    ("AWS Elemental MediaLive", "AWS/MediaLive"),
    ("AWS Elemental MediaPackage", "AWS/MediaPackage"),
    ("AWS Elemental MediaStore", "AWS/MediaStore"),
    ("AWS Elemental MediaTailor", "AWS/MediaTailor"),
    ("AWS End User Messaging SMS", "AWS/SMSVoice"),
    ("AWS End User Messaging Social", "AWS/SocialMessaging"),
    ("Amazon FinSpace", "AWS/FinSpace"),
    ("Amazon Forecast", "AWS/Forecast"),
    ("Amazon Fraud Detector", "AWS/FraudDetector"),
    ("Amazon FSx", "AWS/FSx"),
    ("Amazon GameLift Servers", "AWS/GameLift"),
    ("AWS Glue", "Glue"),
    ("AWS Ground Station", "AWS/GroundStation"),
    ("AWS HealthLake", "AWS/HealthLake"),
    ("Amazon Inspector", "AWS/Inspector"),
    ("Amazon Interactive Video Service", "AWS/IVS"),
    ("Amazon Interactive Video Service Chat", "AWS/IVSChat"),
    ("AWS IoT", "AWS/IoT"),
    ("AWS IoT FleetWise", "AWS/IoTFleetWise"),
    ("AWS IoT SiteWise", "AWS/IoTSiteWise"),
    ("AWS IoT TwinMaker", "AWS/IoTTwinMaker"),
    ("Amazon Keyspaces (for Apache Cassandra)", "AWS/Cassandra"),
    ("Amazon Kendra", "AWS/Kendra"),
    ("Amazon Managed Service for Apache Flink", "AWS/KinesisAnalytics"),
    ("Amazon Kinesis Video Streams", "AWS/KinesisVideo"),
    ("Amazon Lex", "AWS/Lex"),
    ("AWS License Manager", "AWSLicenseManager/licenseUsage"),
    ("Amazon Location Service", "AWS/Location"),
    ("Amazon Lookout for Equipment", "AWS/lookoutequipment"),
    ("Amazon Lookout for Vision", "AWS/LookoutVision"),
    ("AWS Mainframe Modernization", "AWS/M2"),
    ("Amazon Machine Learning", "AWS/ML"),
    ("Amazon Managed Blockchain", "AWS/managedblockchain"),
    ("Amazon Managed Service for Prometheus", "AWS/Prometheus"),
    ("Amazon Managed Streaming for Apache Kafka Connect", "AWS/KafkaConnect"),
    ("Amazon Managed Workflows for Apache Airflow", "AWS/MWAA"),
    ("Amazon MQ", "AWS/AmazonMQ"),
    ("AWS Network Firewall", "AWS/NetworkFirewall"),
    ("AWS Network Manager", "AWS/NetworkManager"),
    ("AWS HealthOmics", "AWS/Omics"),
    ("AWS Outposts", "AWS/Outposts"),
    ("AWS Panorama", "AWS/PanoramaDeviceMetrics"),
    ("Amazon Personalize", "AWS/Personalize"),
    ("Amazon Pinpoint", "AWS/Pinpoint"),
    ("Amazon Polly", "AWS/Polly"),
    ("AWS PrivateLink (Endpoints)", "AWS/PrivateLinkEndpoints"),
    ("AWS PrivateLink (Services)", "AWS/PrivateLinkServices"),
    ("AWS Private 5G", "AWS/Private5G"),
    ("Amazon Q Apps", "AWS/QApps"),
    ("Amazon Q Business", "AWS/QBusiness"),
    ("Amazon Q Developer", "AWS/Q"),
    ("Amazon Quick (QuickSight)", "AWS/QuickSight"),
    ("Amazon Rekognition", "AWS/Rekognition"),
    ("AWS re:Post Private", "AWS/rePostPrivate"),
    ("Route 53 Application Recovery Controller", "AWS/Route53RecoveryReadiness"),
    ("Amazon SageMaker AI", "AWS/SageMaker"),
    ("Amazon SageMaker AI Model Building Pipelines", "AWS/SageMaker/ModelBuildingPipeline"),
    ("AWS Secrets Manager", "AWS/SecretsManager"),
    ("Amazon Security Lake", "AWS/SecurityLake"),
    ("Service Catalog", "AWS/ServiceCatalog"),
    ("AWS Shield Advanced", "AWS/DDoSProtection"),
    ("Amazon Simple Email Service", "AWS/SES"),
    ("S3 Storage Lens", "AWS/S3/Storage-Lens"),
    ("Amazon Simple Workflow Service", "AWS/SWF"),
    ("AWS Storage Gateway", "AWS/StorageGateway"),
    ("AWS Systems Manager Run Command", "AWS/SSM-RunCommand"),
    ("Amazon Textract", "AWS/Textract"),
    ("Amazon Timestream", "AWS/Timestream"),
    ("AWS Transfer for SFTP", "AWS/Transfer"),
    ("Amazon Transcribe", "AWS/Transcribe"),
    ("Amazon Translate", "AWS/Translate"),
    ("AWS Trusted Advisor", "AWS/TrustedAdvisor"),
    ("Amazon VPC IP Address Manager", "AWS/IPAM"),
    ("AWS WAF Classic", "WAF"),
    ("Amazon WorkMail", "AWS/WorkMail"),
    ("Amazon WorkSpaces", "AWS/WorkSpaces"),
    ("Amazon WorkSpaces Web", "AWS/WorkSpacesWeb"),
]
