# app/api/incidents.py
"""
Read endpoints for AIOps roadmap Phase 1 (2026-09-14): correlated
incidents, per-resource health scores, and capacity-exhaustion
forecasts. Gated on incidents.view (db/migrations/026_aiops_phase1.sql)
-- granted to viewer/editor/admin by default, matching this being a
read-only observability surface with no write/manage action in this
phase (incidents are entirely system-generated by
app/collector/correlate.py; nothing here lets a user create/edit one).

Scoped per-account like alerts/resources (not global like op-events),
since incidents are tied to a specific AWS account's resources.
"""
from fastapi import APIRouter, HTTPException, Query, Depends
from app.db import get_connection
from app.auth.permissions import require_permission
from app.auth.authorization import get_accessible_account_ids

router = APIRouter(prefix="/api/incidents", tags=["Incidents"])


def _require_account_access(account_id: int, current_user: dict) -> None:
    accessible = get_accessible_account_ids(current_user)
    if accessible is not None and account_id not in accessible:
        raise HTTPException(status_code=403, detail="You do not have access to this account")


@router.get("/{account_id}")
def list_incidents(
    account_id: int,
    status: str = Query(None, description="Filter by 'active' or 'resolved'"),
    limit: int = Query(50, le=200),
    current_user: dict = Depends(require_permission("incidents.view")),
):
    """List correlated incidents for one account, most recent first."""
    _require_account_access(account_id, current_user)
    conn = get_connection()
    cur = conn.cursor(dictionary=True)
    try:
        query = """
            SELECT i.id, i.title, i.severity, i.status, i.primary_resource_id,
                   i.probable_cause, i.started_at, i.resolved_at, i.last_seen_at,
                   COUNT(ia.alert_id) AS alert_count
            FROM incidents i
            LEFT JOIN incident_alerts ia ON ia.incident_id = i.id
            WHERE i.aws_account_id = %s
        """
        params = [account_id]
        if status:
            query += " AND i.status = %s"
            params.append(status)
        query += " GROUP BY i.id ORDER BY i.last_seen_at DESC LIMIT %s"
        params.append(limit)

        cur.execute(query, params)
        return cur.fetchall()
    finally:
        cur.close()
        conn.close()


@router.get("/{account_id}/{incident_id}/detail")
def get_incident_detail(
    account_id: int,
    incident_id: int,
    current_user: dict = Depends(require_permission("incidents.view")),
):
    """
    One incident's full detail: member alerts, topology-adjacency
    context, and the probable-root-cause ranking (recomputed fresh on
    open, not just whatever was cached at correlation time, so the RCA
    reflects any alerts attached since the incident was created).
    """
    _require_account_access(account_id, current_user)
    conn = get_connection()
    cur = conn.cursor(dictionary=True)
    try:
        cur.execute("""
            SELECT id, title, severity, status, primary_resource_id,
                   probable_cause, started_at, resolved_at, last_seen_at
            FROM incidents WHERE id = %s AND aws_account_id = %s
        """, (incident_id, account_id))
        incident = cur.fetchone()
        if not incident:
            raise HTTPException(status_code=404, detail="Incident not found")

        cur.execute("""
            SELECT a.id, a.resource_id, a.metric_name, a.value, a.severity,
                   a.status, a.created_at
            FROM incident_alerts ia
            JOIN alerts a ON a.id = ia.alert_id
            WHERE ia.incident_id = %s
            ORDER BY a.created_at ASC
        """, (incident_id,))
        incident["alerts"] = cur.fetchall()
    finally:
        cur.close()
        conn.close()

    from app.collector.rca import rank_probable_cause
    rca = rank_probable_cause(incident_id)
    incident["rca"] = rca
    return incident


@router.get("/{account_id}/health")
def list_resource_health(
    account_id: int,
    current_user: dict = Depends(require_permission("incidents.view")),
):
    """
    Health scores for currently-breaching resources in this account
    (see app/collector/health_score.py -- a resource absent from this
    list is implicitly fully healthy, not scored as 0)."""
    _require_account_access(account_id, current_user)
    conn = get_connection()
    cur = conn.cursor(dictionary=True)
    try:
        cur.execute("""
            SELECT resource_id, health_score, score_reason, computed_at
            FROM resource_health
            WHERE aws_account_id = %s
            ORDER BY health_score ASC
        """, (account_id,))
        return cur.fetchall()
    finally:
        cur.close()
        conn.close()


@router.get("/{account_id}/forecast/{resource_id}")
def get_capacity_forecast(
    account_id: int,
    resource_id: str,
    current_user: dict = Depends(require_permission("incidents.view")),
):
    """Capacity-exhaustion forecast (see app/collector/trend.py) for one
    resource's tracked capacity metrics -- empty list if none are
    currently trending toward exhaustion."""
    _require_account_access(account_id, current_user)
    from app.collector.trend import compute_capacity_forecasts
    return compute_capacity_forecasts(aws_resource_id=resource_id)
