# app/api/incidents.py
"""
Read endpoints for AIOps roadmap Phase 1 (2026-09-14): correlated
incidents, per-resource health scores, and capacity-exhaustion
forecasts. Gated on incidents.view (db/migrations/026_aiops_phase1.sql)
-- granted to viewer/editor/admin by default, matching this being a
read-only observability surface with no write/manage action in this
phase (incidents are entirely system-generated by
app/collector/correlate.py; nothing here lets a user create/edit one).

Scoped per-account like alerts/resources (not global like op-events),
since incidents are tied to a specific AWS account's resources.
"""
from fastapi import APIRouter, HTTPException, Query, Depends
import json
from app.db import get_connection
from app.auth.permissions import require_permission
from app.auth.authorization import get_accessible_account_ids

router = APIRouter(prefix="/api/incidents", tags=["Incidents"])


def _require_account_access(account_id: int, current_user: dict) -> None:
    accessible = get_accessible_account_ids(current_user)
    if accessible is not None and account_id not in accessible:
        raise HTTPException(status_code=403, detail="You do not have access to this account")


# ── FLEET-WIDE HEALTH SUMMARY (2026-09-14) ───────────────────────────
# Registered BEFORE /{account_id} below -- FastAPI/Starlette match
# routes in registration order, and "fleet-summary" would otherwise
# match the /{account_id} pattern first (any string matches a path
# param at the routing layer; the int-cast failure only surfaces
# AFTER matching, as a 422, never falling through to try this route).
@router.get("/fleet-summary")
def fleet_health_summary(current_user: dict = Depends(require_permission("incidents.view"))):
    """
    One-call aggregate across every account this user can see: how many
    resources are currently unhealthy (any active alert), how many are
    critically unhealthy (health_score < 70), the 5 worst-scoring
    resources, and how many resources are trending toward a capacity
    limit. Built for a top-of-page executive summary (Overview.jsx) --
    computing this client-side would mean one API call per account;
    this does it server-side in one round trip, correctly scoped to
    exactly the accounts this user is allowed to see (get_accessible_
    account_ids), not a superset.
    """
    accessible = get_accessible_account_ids(current_user)
    if accessible is not None and not accessible:
        # Explicitly scoped to zero accounts -- nothing to aggregate,
        # and no reason to run any query at all.
        return {"unhealthy_resource_count": 0, "critical_resource_count": 0,
                "capacity_risk_count": 0, "worst_resources": []}

    conn = get_connection()
    cur = conn.cursor(dictionary=True)
    try:
        where_clause = ""
        params = []
        if accessible is not None:
            placeholders = ",".join(["%s"] * len(accessible))
            where_clause = f" WHERE aws_account_id IN ({placeholders})"
            params = list(accessible)

        cur.execute(f"""
            SELECT COUNT(*) AS total,
                   SUM(CASE WHEN health_score < 70 THEN 1 ELSE 0 END) AS critical
            FROM resource_health{where_clause}
        """, params)
        counts = cur.fetchone()

        cur.execute(f"""
            SELECT resource_id, aws_account_id, health_score, score_reason
            FROM resource_health{where_clause}
            ORDER BY health_score ASC
            LIMIT 5
        """, params)
        worst = cur.fetchall()
        for row in worst:
            if isinstance(row.get("score_reason"), str):
                try:
                    row["score_reason"] = json.loads(row["score_reason"])
                except Exception:
                    row["score_reason"] = {}
    finally:
        cur.close()
        conn.close()

    from app.collector.trend import compute_capacity_forecasts
    forecasts = compute_capacity_forecasts(aws_account_ids=accessible)

    return {
        "unhealthy_resource_count": counts["total"] or 0,
        "critical_resource_count": counts["critical"] or 0,
        "capacity_risk_count": len(forecasts),
        "worst_resources": worst,
    }


@router.get("/{account_id}")
def list_incidents(
    account_id: int,
    status: str = Query(None, description="Filter by 'active' or 'resolved'"),
    limit: int = Query(50, le=200),
    current_user: dict = Depends(require_permission("incidents.view")),
):
    """List correlated incidents for one account, most recent first."""
    _require_account_access(account_id, current_user)
    conn = get_connection()
    cur = conn.cursor(dictionary=True)
    try:
        query = """
            SELECT i.id, i.title, i.severity, i.status, i.primary_resource_id,
                   i.probable_cause, i.started_at, i.resolved_at, i.last_seen_at,
                   COUNT(ia.alert_id) AS alert_count
            FROM incidents i
            LEFT JOIN incident_alerts ia ON ia.incident_id = i.id
            WHERE i.aws_account_id = %s
        """
        params = [account_id]
        if status:
            query += " AND i.status = %s"
            params.append(status)
        query += " GROUP BY i.id ORDER BY i.last_seen_at DESC LIMIT %s"
        params.append(limit)

        cur.execute(query, params)
        return cur.fetchall()
    finally:
        cur.close()
        conn.close()


@router.get("/{account_id}/{incident_id}/detail")
def get_incident_detail(
    account_id: int,
    incident_id: int,
    current_user: dict = Depends(require_permission("incidents.view")),
):
    """
    One incident's full detail: member alerts, topology-adjacency
    context, and the probable-root-cause ranking (recomputed fresh on
    open, not just whatever was cached at correlation time, so the RCA
    reflects any alerts attached since the incident was created).
    """
    _require_account_access(account_id, current_user)
    conn = get_connection()
    cur = conn.cursor(dictionary=True)
    try:
        cur.execute("""
            SELECT id, title, severity, status, primary_resource_id,
                   probable_cause, started_at, resolved_at, last_seen_at
            FROM incidents WHERE id = %s AND aws_account_id = %s
        """, (incident_id, account_id))
        incident = cur.fetchone()
        if not incident:
            raise HTTPException(status_code=404, detail="Incident not found")

        cur.execute("""
            SELECT a.id, a.resource_id, a.metric_name, a.current_value AS value, a.severity,
                   a.status, a.triggered_at AS created_at
            FROM incident_alerts ia
            JOIN alerts a ON a.id = ia.alert_id
            WHERE ia.incident_id = %s
            ORDER BY a.triggered_at ASC
        """, (incident_id,))
        incident["alerts"] = cur.fetchall()
    finally:
        cur.close()
        conn.close()

    from app.collector.rca import rank_probable_cause
    rca = rank_probable_cause(incident_id)
    incident["rca"] = rca
    return incident


@router.get("/{account_id}/health")
def list_resource_health(
    account_id: int,
    current_user: dict = Depends(require_permission("incidents.view")),
):
    """
    Health scores for currently-breaching resources in this account
    (see app/collector/health_score.py -- a resource absent from this
    list is implicitly fully healthy, not scored as 0)."""
    _require_account_access(account_id, current_user)
    conn = get_connection()
    cur = conn.cursor(dictionary=True)
    try:
        cur.execute("""
            SELECT resource_id, health_score, score_reason, computed_at
            FROM resource_health
            WHERE aws_account_id = %s
            ORDER BY health_score ASC
        """, (account_id,))
        rows = cur.fetchall()
        # BUG FIX (2026-09-14): score_reason is a JSON column -- this
        # driver (mysql-connector, use_pure=True, see app/db.py) returns
        # JSON columns as raw strings, not parsed dicts, same as every
        # other JSON column in this app (resources.tags, always
        # json.loads()'d before use -- see alert_evaluator.py,
        # multivariate_anomaly.py). This endpoint skipped that step, so
        # the frontend received a STRING it couldn't dot-access
        # (health.score_reason.critical_alerts on a string is
        # undefined), silently falling back to the generic "lowered by
        # alert(s)" text instead of the real breakdown -- exactly what
        # showed up in production.
        for row in rows:
            if isinstance(row.get("score_reason"), str):
                try:
                    row["score_reason"] = json.loads(row["score_reason"])
                except Exception:
                    row["score_reason"] = {}
        return rows
    finally:
        cur.close()
        conn.close()


@router.get("/{account_id}/forecast/{resource_id}")
def get_capacity_forecast(
    account_id: int,
    resource_id: str,
    current_user: dict = Depends(require_permission("incidents.view")),
):
    """Capacity-exhaustion forecast (see app/collector/trend.py) for one
    resource's tracked capacity metrics -- empty list if none are
    currently trending toward exhaustion."""
    _require_account_access(account_id, current_user)
    from app.collector.trend import compute_capacity_forecasts
    return compute_capacity_forecasts(aws_resource_id=resource_id)
