# app/api/incidents.py
"""
Read endpoints for AIOps roadmap Phase 1 (2026-09-14): correlated
incidents, per-resource health scores, and capacity-exhaustion
forecasts. Gated on incidents.view (db/migrations/026_aiops_phase1.sql)
-- granted to viewer/editor/admin by default, matching this being a
read-only observability surface with no write/manage action in this
phase (incidents are entirely system-generated by
app/collector/correlate.py; nothing here lets a user create/edit one).

Scoped per-account like alerts/resources (not global like op-events),
since incidents are tied to a specific AWS account's resources.
"""
from fastapi import APIRouter, HTTPException, Query, Depends
import json
import threading
import time
from app.db import get_connection
from app.auth.permissions import require_permission
from app.auth.authorization import get_accessible_account_ids

router = APIRouter(prefix="/api/incidents", tags=["Incidents"])

# Audit C3: fleet-summary AND fleet-detail each called compute_capacity_forecasts(),
# which fits a linear trend over 14 days of history for every capacity metric of every
# resource (measured 3.5-5.9 s per call, issued twice per Overview refresh, identical
# result). The forecast changes on the scale of hours, so one result per scope is reused
# for _FORECAST_TTL seconds and shared by both endpoints. Keyed by the caller's account
# scope (never a superset), so a scoped viewer never sees another account's forecast.
_FORECAST_TTL = 120
_forecast_cache: dict = {}
_forecast_lock = threading.Lock()


def _scope_key(accessible):
    return None if accessible is None else tuple(sorted(accessible))


def _capacity_forecasts_cached(accessible):
    key = _scope_key(accessible)
    now = time.time()
    hit = _forecast_cache.get(key)
    if hit and now - hit[0] < _FORECAST_TTL:
        return hit[1]
    with _forecast_lock:
        hit = _forecast_cache.get(key)          # another request may have filled it while we waited
        if hit and time.time() - hit[0] < _FORECAST_TTL:
            return hit[1]
        from app.collector.trend import compute_capacity_forecasts
        result = compute_capacity_forecasts(aws_account_ids=accessible)
        if len(_forecast_cache) > 64:           # bound memory: scopes are few, but never unbounded
            _forecast_cache.clear()
        _forecast_cache[key] = (time.time(), result)
        return result


def _require_account_access(account_id: int, current_user: dict) -> None:
    accessible = get_accessible_account_ids(current_user)
    if accessible is not None and account_id not in accessible:
        raise HTTPException(status_code=403, detail="You do not have access to this account")


# ── FLEET-WIDE HEALTH SUMMARY (2026-09-14) ───────────────────────────
# Registered BEFORE /{account_id} below -- FastAPI/Starlette match
# routes in registration order, and "fleet-summary" would otherwise
# match the /{account_id} pattern first (any string matches a path
# param at the routing layer; the int-cast failure only surfaces
# AFTER matching, as a 422, never falling through to try this route).
@router.get("/fleet-summary")
def fleet_health_summary(current_user: dict = Depends(require_permission("incidents.view"))):
    """
    One-call aggregate across every account this user can see: how many
    resources are currently unhealthy (any active alert), how many are
    critically unhealthy (health_score < 70), the 5 worst-scoring
    resources, and how many resources are trending toward a capacity
    limit. Built for a top-of-page executive summary (Overview.jsx) --
    computing this client-side would mean one API call per account;
    this does it server-side in one round trip, correctly scoped to
    exactly the accounts this user is allowed to see (get_accessible_
    account_ids), not a superset.
    """
    accessible = get_accessible_account_ids(current_user)
    if accessible is not None and not accessible:
        # Explicitly scoped to zero accounts -- nothing to aggregate,
        # and no reason to run any query at all.
        return {"unhealthy_resource_count": 0, "critical_resource_count": 0,
                "capacity_risk_count": 0, "likely_flapping_count": 0, "worst_resources": []}

    conn = get_connection()
    cur = conn.cursor(dictionary=True)
    try:
        where_clause = ""
        params = []
        if accessible is not None:
            placeholders = ",".join(["%s"] * len(accessible))
            where_clause = f" WHERE aws_account_id IN ({placeholders})"
            params = list(accessible)

        cur.execute(f"""
            SELECT COUNT(*) AS total,
                   SUM(CASE WHEN health_score < 70 THEN 1 ELSE 0 END) AS critical
            FROM resource_health{where_clause}
        """, params)
        counts = cur.fetchone()

        cur.execute(f"""
            SELECT resource_id, aws_account_id, health_score, score_reason
            FROM resource_health{where_clause}
            ORDER BY health_score ASC
            LIMIT 5
        """, params)
        worst = cur.fetchall()
        for row in worst:
            if isinstance(row.get("score_reason"), str):
                try:
                    row["score_reason"] = json.loads(row["score_reason"])
                except Exception:
                    row["score_reason"] = {}
    finally:
        cur.close()
        conn.close()

    forecasts = _capacity_forecasts_cached(accessible)

    from app.collector.threshold_tuning import count_likely_flapping_alerts
    flapping_count = count_likely_flapping_alerts(aws_account_ids=accessible)

    return {
        "unhealthy_resource_count": counts["total"] or 0,
        "critical_resource_count": counts["critical"] or 0,
        "capacity_risk_count": len(forecasts),
        "likely_flapping_count": flapping_count,
        "worst_resources": worst,
    }


@router.get("/fleet-detail")
def fleet_health_detail(current_user: dict = Depends(require_permission("incidents.view"))):
    """
    The LISTS behind the Overview "Need Attention" tile, so the numbers on the tile
    are clickable: `critical_resources` (health score < 70 -- exactly what
    fleet-summary's critical_resource_count counts) and `capacity_risks` (exactly
    fleet-summary's capacity_risk_count). Scoped like fleet-summary.
    """
    accessible = get_accessible_account_ids(current_user)
    if accessible is not None and not accessible:
        return {"critical_resources": [], "capacity_risks": []}

    conn = get_connection()
    cur = conn.cursor(dictionary=True)
    try:
        where, params = "", []
        if accessible is not None:
            where = " AND h.aws_account_id IN (" + ",".join(["%s"] * len(accessible)) + ")"
            params = list(accessible)
        cur.execute(f"""
            SELECT h.resource_id, h.aws_account_id, MIN(h.health_score) AS health_score,
                   MAX(h.score_reason) AS score_reason,
                   MAX(r.name) AS resource_name, MAX(r.resource_type) AS resource_type,
                   MAX(acc.account_name) AS account_name
            FROM resource_health h
            LEFT JOIN resources r ON r.resource_id = h.resource_id AND r.aws_account_id = h.aws_account_id
            LEFT JOIN aws_accounts acc ON acc.id = h.aws_account_id
            WHERE h.health_score < 70{where}
            GROUP BY h.aws_account_id, h.resource_id
            ORDER BY health_score ASC
            LIMIT 200
        """, params)
        critical = cur.fetchall()
        for row in critical:
            if isinstance(row.get("score_reason"), str):
                try:
                    row["score_reason"] = json.loads(row["score_reason"])
                except Exception:
                    row["score_reason"] = {}
            row["health_score"] = float(row["health_score"]) if row["health_score"] is not None else None

        forecasts = _capacity_forecasts_cached(accessible)
        names = {}
        if forecasts:
            ids = sorted({f["resource_id"] for f in forecasts})
            cur.execute(f"""
                SELECT r.aws_account_id, r.resource_id, MAX(r.name) AS name, MAX(r.resource_type) AS resource_type,
                       MAX(acc.account_name) AS account_name
                FROM resources r LEFT JOIN aws_accounts acc ON acc.id = r.aws_account_id
                WHERE r.resource_id IN ({",".join(["%s"] * len(ids))})
                GROUP BY r.aws_account_id, r.resource_id
            """, ids)
            names = {(n["aws_account_id"], n["resource_id"]): n for n in cur.fetchall()}
    finally:
        cur.close()
        conn.close()

    risks = []
    for f in forecasts:
        n = names.get((f["aws_account_id"], f["resource_id"]), {})
        risks.append({**f, "resource_name": n.get("name") or f["resource_id"],
                      "resource_type": n.get("resource_type"), "account_name": n.get("account_name")})
    risks.sort(key=lambda x: x.get("days_to_exhaustion") if x.get("days_to_exhaustion") is not None else 1e9)
    return {"critical_resources": critical, "capacity_risks": risks}


@router.get("/{account_id}")
def list_incidents(
    account_id: int,
    status: str = Query(None, description="Filter by 'active' or 'resolved'"),
    limit: int = Query(50, ge=1, le=200),
    current_user: dict = Depends(require_permission("incidents.view")),
):
    """List correlated incidents for one account, most recent first."""
    _require_account_access(account_id, current_user)
    conn = get_connection()
    cur = conn.cursor(dictionary=True)
    try:
        query = """
            SELECT i.id, i.title, i.severity, i.status, i.primary_resource_id,
                   i.probable_cause, i.started_at, i.resolved_at, i.last_seen_at,
                   COUNT(ia.alert_id) AS alert_count
            FROM incidents i
            LEFT JOIN incident_alerts ia ON ia.incident_id = i.id
            WHERE i.aws_account_id = %s
        """
        params = [account_id]
        if status:
            query += " AND i.status = %s"
            params.append(status)
        query += " GROUP BY i.id ORDER BY i.last_seen_at DESC LIMIT %s"
        params.append(limit)

        cur.execute(query, params)
        return cur.fetchall()
    finally:
        cur.close()
        conn.close()


@router.get("/{account_id}/{incident_id}/detail")
def get_incident_detail(
    account_id: int,
    incident_id: int,
    current_user: dict = Depends(require_permission("incidents.view")),
):
    """
    One incident's full detail: member alerts, topology-adjacency
    context, and the probable-root-cause ranking (recomputed fresh on
    open, not just whatever was cached at correlation time, so the RCA
    reflects any alerts attached since the incident was created).
    """
    _require_account_access(account_id, current_user)
    conn = get_connection()
    cur = conn.cursor(dictionary=True)
    try:
        cur.execute("""
            SELECT id, title, severity, status, primary_resource_id,
                   probable_cause, started_at, resolved_at, last_seen_at
            FROM incidents WHERE id = %s AND aws_account_id = %s
        """, (incident_id, account_id))
        incident = cur.fetchone()
        if not incident:
            raise HTTPException(status_code=404, detail="Incident not found")

        cur.execute("""
            SELECT a.id, a.resource_id, a.metric_name, a.current_value AS value, a.severity,
                   a.status, a.triggered_at AS created_at
            FROM incident_alerts ia
            JOIN alerts a ON a.id = ia.alert_id
            WHERE ia.incident_id = %s
            ORDER BY a.triggered_at ASC
        """, (incident_id,))
        incident["alerts"] = cur.fetchall()
    finally:
        cur.close()
        conn.close()

    from app.collector.rca import rank_probable_cause
    rca = rank_probable_cause(incident_id)
    incident["rca"] = rca
    return incident


@router.get("/{account_id}/health")
def list_resource_health(
    account_id: int,
    current_user: dict = Depends(require_permission("incidents.view")),
):
    """
    Health scores for currently-breaching resources in this account
    (see app/collector/health_score.py -- a resource absent from this
    list is implicitly fully healthy, not scored as 0)."""
    _require_account_access(account_id, current_user)
    conn = get_connection()
    cur = conn.cursor(dictionary=True)
    try:
        cur.execute("""
            SELECT resource_id, health_score, score_reason, computed_at
            FROM resource_health
            WHERE aws_account_id = %s
            ORDER BY health_score ASC
        """, (account_id,))
        rows = cur.fetchall()
        # BUG FIX (2026-09-14): score_reason is a JSON column -- this
        # driver (mysql-connector, use_pure=True, see app/db.py) returns
        # JSON columns as raw strings, not parsed dicts, same as every
        # other JSON column in this app (resources.tags, always
        # json.loads()'d before use -- see alert_evaluator.py,
        # multivariate_anomaly.py). This endpoint skipped that step, so
        # the frontend received a STRING it couldn't dot-access
        # (health.score_reason.critical_alerts on a string is
        # undefined), silently falling back to the generic "lowered by
        # alert(s)" text instead of the real breakdown -- exactly what
        # showed up in production.
        for row in rows:
            if isinstance(row.get("score_reason"), str):
                try:
                    row["score_reason"] = json.loads(row["score_reason"])
                except Exception:
                    row["score_reason"] = {}
        return rows
    finally:
        cur.close()
        conn.close()


@router.get("/{account_id}/forecast/{resource_id}")
def get_capacity_forecast(
    account_id: int,
    resource_id: str,
    current_user: dict = Depends(require_permission("incidents.view")),
):
    """Capacity-exhaustion forecast (see app/collector/trend.py) for one
    resource's tracked capacity metrics -- empty list if none are
    currently trending toward exhaustion."""
    _require_account_access(account_id, current_user)
    from app.collector.trend import compute_capacity_forecasts
    # AUDIT(b06): must pass the account too. resource_id is only unique
    # WITHIN an account (see alerts._get_alert_account_id), so filtering by
    # resource_id alone fitted the trend over metric_history points from
    # every account sharing that id -- leaking another tenant's capacity
    # data into this one AND corrupting the regression itself.
    return compute_capacity_forecasts(aws_resource_id=resource_id, aws_account_ids=[account_id])
