# app/metric_labels.py
"""
Human wording for stored metric names, for anything server-side that a person reads (RCA reports, emails, exports).

The UI has had one source for this since the metric-label work (frontend/src/utils/metricLabels.js, generated by
scripts/generate_metric_labels.py from the seed metric catalogues). This module is the Python side of the SAME thing:
the generator imports its tokenizer/acronym tables from here and also writes app/metric_labels_generated.py, so a report
says "Volume Read Operations", exactly like the Alerts page, and not the raw key "VolumeReadOps".

    metric_label("volumereadops")                 -> "Volume Read Operations"
    metric_label("disk_used_percent__var_lib")    -> "Disk Utilization (/var/lib)"
    format_metric_value("cpuutilization", 95.134) -> "95.13%"
"""
import re

ACRONYMS = {
    "cpu": "CPU", "io": "I/O", "iops": "IOPS", "http": "HTTP", "https": "HTTPS", "db": "DB", "dns": "DNS",
    "tcp": "TCP", "udp": "UDP", "ssl": "SSL", "tls": "TLS", "api": "API", "ip": "IP", "id": "ID",
    "kms": "KMS", "sqs": "SQS", "sns": "SNS", "vpn": "VPN", "nat": "NAT", "ebs": "EBS", "ec2": "EC2",
    "s3": "S3", "efs": "EFS", "ttl": "TTL", "lb": "LB", "vm": "VM", "os": "OS", "sql": "SQL",
    "jvm": "JVM", "url": "URL", "acl": "ACL", "msk": "MSK", "eks": "EKS", "ecs": "ECS", "az": "AZ",
    "aws": "AWS", "waf": "WAF", "elb": "ELB", "alb": "ALB", "nlb": "NLB", "rds": "RDS", "gpu": "GPU",
    "ssd": "SSD", "hdd": "HDD", "ram": "RAM", "tps": "TPS", "qps": "QPS", "ok": "OK", "gc": "GC",
    "kb": "KB", "mb": "MB", "gb": "GB", "tb": "TB", "utc": "UTC", "arn": "ARN", "iam": "IAM",
    "sdk": "SDK", "ssh": "SSH", "cdn": "CDN", "gke": "GKE", "gce": "GCE", "gcs": "GCS", "vpc": "VPC",
    "dtu": "DTU", "dip": "DIP", "vip": "VIP", "cdc": "CDC", "ru": "RU", "wlm": "WLM", "syn": "SYN",
    "bps": "BPS", "sparql": "SPARQL", "mysql": "MySQL", "postgresql": "PostgreSQL",
}
LOWER_WORDS = {"per", "of", "to", "and", "for", "by", "from"}
WORD_MAP = {"ops": "Operations", "sec": "Second", "mem": "Memory", "avg": "Average", "num": "Number",
            "conns": "Connections", "conn": "Connection", "msgs": "Messages", "req": "Requests"}

_TOKEN = r"[A-Z]+(?=[A-Z][a-z])|[A-Z]?[a-z]+|[A-Z]+[0-9]*|[0-9]+[A-Z]*(?![a-z])|[0-9]+[a-z]*"


def _tokens(name):
    s = re.sub(r"/sec\b", " per second", name, flags=re.I)
    s = re.sub(r"[/_.\-]", " ", s)
    out = []
    for part in s.split():
        out += re.findall(_TOKEN, part)
    return out


def humanize(name):
    words = []
    for i, tok in enumerate(_tokens(name)):
        low = tok.lower()
        if low in ACRONYMS:
            w = ACRONYMS[low]
        elif low in WORD_MAP:
            w = WORD_MAP[low]
        elif re.fullmatch(r"[0-9]+[A-Za-z]*", tok):        # 5XX -> 5xx, 4xx, 2xx
            w = tok.lower()
        elif i > 0 and low in LOWER_WORDS:
            w = low
        else:
            w = tok[0].upper() + tok[1:].lower() if tok.isupper() or tok.islower() else tok
        words.append(w)
    return " ".join(words)


_MOUNT = re.compile(r"^(disk_used_percent)__(.+)$")


def _generated():
    try:
        from app import metric_labels_generated as g
        return g.LABELS, frozenset(g.PERCENT_METRICS)
    except Exception:                                      # generated file not built yet: fall back to tokenising
        return {}, frozenset()


def metric_label(name):
    if not name:
        return ""
    raw = str(name)
    lower = raw.lower()
    labels, _ = _generated()
    if lower in labels:
        return labels[lower]
    m = _MOUNT.match(lower)
    if m and m.group(1) in labels:
        return f"{labels[m.group(1)]} (/{m.group(2).replace('_', '/')})"
    return humanize(raw)


def metric_unit(name):
    """'%' for catalogue Percent metrics (and per-mount disk series), else ''."""
    n = str(name or "").lower()
    _, percent = _generated()
    return "%" if n in percent or _MOUNT.match(n) else ""


def format_metric_value(name, v, grouped=False):
    """Compact, unit-aware number (same rules as the UI's formatMetricValue).

    grouped=True adds thousands separators below 10,000 ("1,267"), which reads better in print than the UI's bare "1267".
    """
    if v is None or v == "":
        return "-"
    try:
        n = float(v)
    except (TypeError, ValueError):
        return str(v)
    a = abs(n)
    if a >= 1e12:
        out = f"{n / 1e12:.2f}T"
    elif a >= 1e9:
        out = f"{n / 1e9:.2f}G"
    elif a >= 1e6:
        out = f"{n / 1e6:.2f}M"
    elif a >= 1e4:
        out = f"{n / 1e3:.1f}K"
    elif a != 0 and a < 0.1:
        out = f"{n:.2g}"
    elif n == int(n):
        out = f"{int(n):,}" if grouped else str(int(n))
    else:
        out = (f"{n:,.2f}" if grouped else f"{n:.2f}").rstrip("0").rstrip(".")
    return out + metric_unit(name)
