// src/pages/Incidents.jsx
// AIOps roadmap Phase 1 (2026-09-14): correlated incidents, resource
// health scores, and probable-root-cause analysis. Read-only -- every
// incident here is entirely system-generated by
// app/collector/correlate.py + app/collector/rca.py; there is no
// create/edit action on this page in this phase.
//
// Follows the same card/table/badge language as OpEvents.jsx and
// Compliance.jsx (see those files' own docstrings for why -- the
// original topology/op-events/escalation pages were rebuilt once
// already after shipping with raw, unthemed Tailwind classes).
import { useState, useEffect, useCallback } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { getIncidents, getIncidentDetail, getResourceHealth } from "../api/api";
import { useTimezone } from "../contexts/TimezoneContext";
import { RotateCcwIcon, AlertOctagonIcon, AlertTriangleIcon } from "../components/icons";
import "./Incidents.css";

function SeverityBadge({ sev }) {
  const cls = sev === "CRITICAL" ? "inc-sev inc-sev-critical" : "inc-sev inc-sev-warning";
  return <span className={cls}>● {sev}</span>;
}

function StatusBadge({ status }) {
  return <span className={`inc-status inc-status-${status}`}>{status}</span>;
}

function IncidentRow({ incident, ianaName, accountId }) {
  const [expanded, setExpanded] = useState(false);
  const [detail, setDetail] = useState(null);
  const [loadingDetail, setLoadingDetail] = useState(false);

  const toggle = () => {
    const next = !expanded;
    setExpanded(next);
    if (next && !detail) {
      setLoadingDetail(true);
      getIncidentDetail(accountId, incident.id)
        .then(setDetail)
        .catch(() => setDetail(null))
        .finally(() => setLoadingDetail(false));
    }
  };

  return (
    <div className={`inc-row ${expanded ? "inc-row-expanded" : ""}`}>
      <div className="inc-row-main" onClick={toggle}>
        <span className="inc-icon-wrap">
          {incident.severity === "CRITICAL" ? <AlertOctagonIcon size={14} /> : <AlertTriangleIcon size={14} />}
        </span>
        <div className="inc-body">
          <div className="inc-top-line">
            <span className="inc-title">{incident.title}</span>
            <SeverityBadge sev={incident.severity} />
            <StatusBadge status={incident.status} />
            <span className="inc-alert-count">{incident.alert_count} alert(s)</span>
          </div>
          {incident.probable_cause && (
            <div className="inc-cause">{incident.probable_cause}</div>
          )}
        </div>
        <div className="inc-time">
          <div className="inc-ts">
            {new Date(incident.started_at).toLocaleTimeString("en-US", {
              hour: "2-digit", minute: "2-digit", hour12: false, timeZone: ianaName,
            })}
          </div>
          <div className="inc-date">
            {new Date(incident.started_at).toLocaleDateString("en-GB", { timeZone: ianaName })}
          </div>
        </div>
        <span className="inc-expand">{expanded ? "▲" : "▼"}</span>
      </div>

      {expanded && (
        <div className="inc-detail">
          {loadingDetail && <div className="inc-detail-loading">Loading...</div>}
          {detail && (
            <>
              <div className="inc-detail-section">
                <h4>Member alerts</h4>
                <table className="inc-alert-table">
                  <thead>
                    <tr><th>Resource</th><th>Metric</th><th>Value</th><th>Severity</th><th>Status</th></tr>
                  </thead>
                  <tbody>
                    {detail.alerts.map(a => (
                      <tr key={a.id}>
                        <td>{a.resource_id}</td>
                        <td>{a.metric_name}</td>
                        <td>{a.value}</td>
                        <td><SeverityBadge sev={a.severity} /></td>
                        <td>{a.status}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              {detail.rca && (
                <div className="inc-detail-section">
                  <h4>Probable root cause</h4>
                  <p className="inc-rca-reason">{detail.rca.reason}</p>
                  {detail.rca.cloud_events?.length > 0 && (
                    <>
                      <h5>Real AWS activity around this window</h5>
                      <ul className="inc-cloud-events">
                        {detail.rca.cloud_events.map((e, i) => (
                          <li key={i}>
                            <code>{e.event_name}</code> by {e.username || "unknown"} at{" "}
                            {new Date(e.event_time).toLocaleString("en-US", { timeZone: ianaName })}
                          </li>
                        ))}
                      </ul>
                    </>
                  )}
                  {detail.rca.config_changes?.length > 0 && (
                    <p className="inc-config-warning">
                      A monitoring-hub config change was also made in this window — worth checking
                      whether this is a real incident or a threshold/config edit.
                    </p>
                  )}
                </div>
              )}
            </>
          )}
        </div>
      )}
    </div>
  );
}

function HealthStrip({ health, navigate, accountId }) {
  if (!health.length) return null;
  return (
    <div className="inc-health-strip">
      <h4>Resource health (breaching resources only — everything else is healthy)</h4>
      <div className="inc-health-cards">
        {health.map(h => (
          <div
            key={h.resource_id}
            className="inc-health-card"
            style={{ "--health-color": h.health_score >= 70 ? "var(--warning)" : "var(--danger)" }}
            onClick={() => navigate(`/accounts/${accountId}/topology`)}
          >
            <div className="inc-health-score">{h.health_score}</div>
            <div className="inc-health-resource">{h.resource_id}</div>
          </div>
        ))}
      </div>
    </div>
  );
}

export default function Incidents() {
  const { id: accountId } = useParams();
  const navigate = useNavigate();
  const { ianaName } = useTimezone();
  const [incidents, setIncidents] = useState([]);
  const [health, setHealth] = useState([]);
  const [statusFilter, setStatusFilter] = useState("active");
  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(true);

  const load = useCallback(() => {
    setLoading(true);
    Promise.all([
      getIncidents(accountId, statusFilter ? { status: statusFilter } : {}),
      getResourceHealth(accountId),
    ])
      .then(([incidentsData, healthData]) => {
        setIncidents(Array.isArray(incidentsData) ? incidentsData : []);
        setHealth(Array.isArray(healthData) ? healthData : []);
        setError(null);
      })
      .catch(e => setError(e.message))
      .finally(() => setLoading(false));
  }, [accountId, statusFilter]);

  useEffect(() => { load(); }, [load]);

  return (
    <div className="incidents-page">
      <div className="c-header">
        <div>
          <h1>Incidents <span className="hl">& Health</span></h1>
          <p className="sub">
            Topology-correlated alert groups with probable-root-cause analysis — sourced from real
            AWS CloudTrail activity, not just this app's own logs
          </p>
        </div>
        <div className="c-header-actions">
          <select className="inc-status-select" value={statusFilter} onChange={e => setStatusFilter(e.target.value)}>
            <option value="active">Active</option>
            <option value="resolved">Resolved</option>
            <option value="">All</option>
          </select>
          <button className="c-btn" onClick={load}><RotateCcwIcon size={13} /> Refresh</button>
        </div>
      </div>

      {error && <div className="inc-error">{error}</div>}

      <HealthStrip health={health} navigate={navigate} accountId={accountId} />

      <div className="inc-list">
        {loading && <div className="inc-loading">Loading...</div>}
        {!loading && incidents.length === 0 && (
          <div className="inc-empty">No {statusFilter || ""} incidents — correlated alert groups will appear here.</div>
        )}
        {incidents.map(incident => (
          <IncidentRow key={incident.id} incident={incident} ianaName={ianaName} accountId={accountId} />
        ))}
      </div>
    </div>
  );
}
