#!/usr/bin/env python3
"""
RBAC / authentication matrix generated from the code (audit E5).

Imports the FastAPI app with the database module stubbed (no DB, no network), walks every route's dependency tree and
records what protects it:

  public          no authentication dependency at all
  authenticated   any signed-in user (get_current_user only)
  permission      require_permission("<code>")
  role            require_role("<role>", ...)
  custom          a hand-written guard function (listed by name; each one needs review)

    python3 scripts/rbac_matrix.py            # prints a Markdown table
    python3 scripts/rbac_matrix.py --json     # machine-readable
    python3 scripts/rbac_matrix.py --write docs/RBAC_MATRIX.md

tests/test_audit_p13_rbac_matrix.py uses build_matrix() to fail CI if a new route is public by accident, if a
state-changing route is open to every signed-in user without being reviewed, or if a route names a permission that is
not seeded in any migration.
"""
import inspect
import json
import os
import sys
import types
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MUTATING = {"POST", "PUT", "PATCH", "DELETE"}


def _load_app():
    os.environ.setdefault("DB_PASSWORD", "matrix-mode")
    os.environ.setdefault("JWT_SECRET", "matrix-mode-secret-matrix-mode-secret")
    sys.path.insert(0, str(ROOT))
    if "app.db" not in sys.modules:
        fake = types.ModuleType("app.db")

        def _no_db(*a, **k):
            raise RuntimeError("database is not available in matrix mode")
        fake.get_connection = _no_db
        fake.get_db_cursor = _no_db
        sys.modules["app.db"] = fake
    import app.main as main
    return main.app


def _walk(dependant, found):
    for dep in dependant.dependencies:
        call = dep.call
        name = getattr(call, "__name__", "")
        if name == "get_current_user":
            found["auth"] = True
        else:
            try:
                nonlocals = inspect.getclosurevars(call).nonlocals
            except (TypeError, ValueError):
                nonlocals = {}
            if "code" in nonlocals and isinstance(nonlocals["code"], str):
                found["permissions"].add(nonlocals["code"])
            elif "roles" in nonlocals:
                found["roles"].update(nonlocals["roles"])
            elif name.startswith("_require") or name.startswith("require_"):
                found["custom"].add(name)             # e.g. status_page's _require_view_or_manage
        _walk(dep, found)


def build_matrix(app=None):
    app = app or _load_app()
    rows = []
    for route in app.routes:
        if not hasattr(route, "dependant") or not hasattr(route, "methods"):
            continue
        found = {"auth": False, "permissions": set(), "roles": set(), "custom": set()}
        _walk(route.dependant, found)
        if found["permissions"]:
            level = "permission"
        elif found["roles"]:
            level = "role"
        elif found["custom"]:
            level = "custom"
        elif found["auth"]:
            level = "authenticated"
        else:
            level = "public"
        methods = sorted(m for m in route.methods if m not in ("HEAD", "OPTIONS"))
        rows.append({
            "path": route.path,
            "methods": methods,
            "mutating": bool(set(methods) & MUTATING),
            "level": level,
            "permissions": sorted(found["permissions"]),
            "roles": sorted(found["roles"]),
            "custom": sorted(found["custom"]),
        })
    rows.sort(key=lambda r: (r["path"], r["methods"]))
    return rows


def to_markdown(rows):
    out = ["# RBAC matrix (generated)", "",
           "Generated by `scripts/rbac_matrix.py` from the route dependencies. Regenerate with "
           "`python3 scripts/rbac_matrix.py --write docs/RBAC_MATRIX.md`. Do not edit by hand.", "",
           f"{len(rows)} routes.", "",
           "| Method | Path | Protection | Requires |", "|---|---|---|---|"]
    for r in rows:
        req = ", ".join(r["permissions"] or r["roles"] or r["custom"]) or ("any signed-in user" if r["level"] == "authenticated" else "nothing")
        out.append(f"| {'/'.join(r['methods'])} | `{r['path']}` | {r['level']} | {req} |")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    matrix = build_matrix()
    if "--json" in sys.argv:
        print(json.dumps(matrix, indent=1))
    elif "--write" in sys.argv:
        target = Path(sys.argv[sys.argv.index("--write") + 1])
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(to_markdown(matrix))
        print(f"wrote {target} ({len(matrix)} routes)")
    else:
        print(to_markdown(matrix))
